### ISSUE TITLE
is v0.8.6 work for Mojave?

### ISSUE THREAD

**Issue by jqtmviyu** [yusufklncc/Toshiba-Portege-Z30-Hackintosh#2]
I try v0.8.5-mojave-version and v0.8.6 on Mojave, AirportItlwm.kext not work,  and can't found Bluetooth setting menu.
disable AirportItlwm.kext and inject itlwm.kext, wifi can work with HeliPort.

Whether special settings are required after using the above efi file ?

Or the v0.8.6 version can only work on BigSur best?

(I tried to install the old system, because the cpu and hard drive of the device are so bad, I hope the old version will bring less footprint)

**Comment by jqtmviyu** [comment]
reinstall Monterey and use v0.8.5, Bluetooth and wifi working well. 
(hdmi not work on my pc)

**Comment by yusufklncc** [comment]
You need a securebootmodel for airportitlwm on mojave.
